# https://github.com/alirezanet/publish-nuget
name: Build, test & publish
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        working-directory: idee5.AspNetCore
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --configuration Release --no-build --verbosity normal
    - name: Publish to nuget
      uses: alirezanet/publish-nuget@v3.1.0
      with:
       PROJECT_FILE_PATH: idee5.AspNetCore/idee5.AspNetCore.csproj
       NUGET_KEY: ${{secrets.NUGET_API_KEY}}
       NO_BUILD: true
